dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: ttc-dashboard-ui
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: "activiti-keycloak"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.23"
  condition: "infrastructure.activiti-keycloak.enabled,activiti-keycloak.enabled"
- name: "activiti-cloud-gateway"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.13"
  condition: "infrastructure.activiti-cloud-gateway.enabled,activiti-cloud-gateway.enabled"
