PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 35.229.237.50.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        TILLER_NAMESPACE: kube-system
prow: {}
global:
  keycloak:
    url: "http://activiti-keycloak.jx-staging.35.229.237.50.nip.io/auth"
    realm: "activiti"
    resource: "activiti"
    client: "activiti"

  gateway:
    hostName: "activiti-cloud-gateway.jx-staging.35.229.237.50.nip.io"
    host: "activiti-cloud-gateway.jx-staging.35.229.237.50.nip.io"

activiti-keycloak:
  enabled: false
  ingress:
    enabled: true
  keycloak:
    enabled: true
    keycloak:
      preStartScript: |
        /opt/jboss/keycloak/bin/add-user.sh -u admin -p admin
        /opt/jboss/keycloak/bin/add-user-keycloak.sh -r master -u admin -p admin
        cp /realm/activiti-realm.json .
        sed -i 's/placeholder.com/*/g' activiti-realm.json
  
activiti-cloud-gateway:
  service:
    name: activiti-cloud-gateway
  image:
    repository: activiti/activiti-cloud-gateway
    #tag: 7.0.0.SR1
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "*"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
